### ISSUE TITLE
ODFE support and path forward with fork

### ISSUE THREAD

**Issue by KadekM** [Philippus/elastic4s#2316]
Due to licensing changes in ES, the OpenDistroForElastic will fork last viable ES (7.10) , and since 7.11 is already out they will probably start diverging soon. 

I don't suppose you plan to maintain patches for 7.10 in meantime and in any fashion support both DBs?
If not I may just have to fork this and maintain it for ODFE. What do you think?

**Comment by sksamuel** [comment]
I will probably support both (if both are popular) but I want to see what happens with ODFE first. Will it succeed or fizzle out. I remember when Hudson/Jenkins was forked and Hudson kind of died out. Mabye ODFE will take over and original ES will die out. 

In other words, I'm delaying any decisions until I see what happens over the next month or three. I've also got to do this at the same time as adding dotty support.

I'd be happy for anyone to join as a contributor here, regardless of how we proceed.

**Comment by KadekM** [comment]
Sounds good. So the plan is to have a separate branch for 7.10 release so we can patch it as well in meantime?

**Comment by sksamuel** [comment]
Yes we could do. I guess the only difference right now is the client dependency ?
We could even move the elastic dependency to another module and make it opt in - it's only a HTTP client after all.

**Comment by KadekM** [comment]
I haven't tracked the changelog yet. But I guess in future there'll be more breaking changes so it's something we need to think of.

**Comment by sksamuel** [comment]
I've been reading about it here: https://discuss.opendistrocommunity.dev/c/forking-elasticsearch-kibana/50
So once they have something released we can branch 7.10 for that.

**Comment by sksamuel** [comment]
I don't see much action in the odfe fork at the moment.

**Comment by Philippus** [comment]
I don't think it's feasible to support both OpenSearch and Elasticsearch in elastic4s. The projects are going their separate ways and eventually the api's will diverge, if they haven't already (not sure if OpenSearch has a Synonyms API for example).
If somebody wants to create an opensearch4s, they can create a fork of elastic4s (of version 7.10.x) and go from there.
