### ISSUE TITLE
Support Scala 3

### ISSUE THREAD

**Issue by sksamuel** [Philippus/elastic4s#2359]
Good opportunity for breaking changes (to be listed here).

**Comment by oyvindberg** [comment]
Any progress here, any help needed to get started?

I'd like to kindly note that the scala 3 port is *not* a good opportunity to accumulate breaking changes. The churn required to upgrade is already overwhelming.

**Comment by sksamuel** [comment]
The churn from scala3 or churn in elastic4s?

**Comment by oyvindberg** [comment]
From scala 3, sorry that wasn't clear. We're slowly working through it now. So i just wanted to say that i appreciate any library which saves random breakage until later :)

**Comment by Philippus** [comment]
fixed in https://github.com/Philippus/elastic4s/pull/2736.
