### ISSUE TITLE
Set auto_generate_synonyms_phrase_query parameter in Match query

### ISSUE THREAD

**Issue by maurin-at-homiwoo** [Philippus/elastic4s#2880]
Hi @sksamuel 

First, thanks for this client, it's a really nice work :)

I'm looking for a way to set the auto_generate_synonyms_phrase_query parameter in a match query, but it seems it is not supported by elastic4s. 
Here is the documentation for the field, it takes a boolean parameter and default to true. https://www.elastic.co/guide/en/elasticsearch/reference/8.8/query-dsl-match-query.html#match-field-params

I can make a quick PR for it (for the case class and the builder) if that can help. 

Cheers, 
Moe

**Comment by sksamuel** [comment]
Yep if you want to make a PR that would be great.
