### ISSUE TITLE
Update the mapping of an index

### ISSUE THREAD

**Issue by gaelayo** [Philippus/elastic4s#2917]
Hello, and thank you for the library.

I am trying to find documentation about how to update the mapping of an index (similar to [https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#put-mapping-api-prereqs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#put-mapping-api-prereqs) ), but I can only find the `rollover` method and `createIndex`. 

Edit: I also found the class `PutMappingRequest`, but it does not seem to take a `MappingDefinition` as argument. Is it possible to convert a `MappingDefinition` into a `PutMappingRequest` ?

Thank you

**Comment by tastyminerals** [comment]
Have you tried?
```scala
 def putIndexMapping(indexName: String, mapping: MappingDefinition): Unit = {
    client.execute {
      putMapping(Seq(indexName)).properties(mapping.properties)
    }.await(timeout)
  }
  ```
