### ISSUE TITLE
Add runtime fields support to `MappingDefinitionLike`

### ISSUE THREAD

**Issue by gaelayo** [Philippus/elastic4s#2931]
Hello, and thank you very much for this library.

Currently, it is possible to provide a runtime field definition when making a request, but it does not look possible to define one when creating or updating the mapping of an index, as per [https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-mapping-fields.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-mapping-fields.html).

Do you think it is possible to add support for the runtime fields in the mapping ?

Thank you

**Comment by sksamuel** [comment]
We can add it. If you want to make a PR I'll do the release.

**Comment by Philippus** [comment]
fixed in https://github.com/Philippus/elastic4s/pull/2972
