### ISSUE TITLE
opensearch compatibility

### ISSUE THREAD

**Issue by pparasnis-apixio** [Philippus/elastic4s#2943]
Hi,
Is this library compatible with OpenSearch 2.x?

Thanks!

**Comment by hacetin** [comment]
@sksamuel is there a plan to test is against open search as well? We use elastic4s `7.15.0` and opensearch `2.7`. So far there is o issues.

**Comment by kaan-carbon** [comment]
@sksamuel Do you have any plans to test this library with OpenSearch?

**Comment by sksamuel** [comment]
No. This library is in maintenance mode. I will merge PRs created by people and release them but I no longer use Scala actively.  Also happy to hand over to another maintainer.

**Comment by Philippus** [comment]
👋 I'd be happy to take over the project @sksamuel.

**Comment by sksamuel** [comment]
I've invited you to this repo @Philippus . We can talk about moving it to an org / your repo if you like.

**Comment by Philippus** [comment]
If you can move it to my repo, that would be great.

**Comment by apavlychev** [comment]
@Philippus is there planning for a OpenSearch support ?

**Comment by Philippus** [comment]
I don't think it's feasible to support both OpenSearch and Elasticsearch in elastic4s. The projects are going their separate ways and eventually the api's will diverge, if they haven't already (not sure if OpenSearch has a Synonyms API for example).
If somebody wants to create an opensearch4s, they can create a fork of elastic4s (of version 7.10.x) and go from there.

**Comment by hacetin** [comment]
@Philippus have you created the fork yet?
