### ISSUE TITLE
ElasticProperties accepts invalid input and runs with only single node

### ISSUE THREAD

**Issue by felixbr** [Philippus/elastic4s#2961]
Hi, 

we ran into a config issue which caused a small outage because our code only connected to one ES node of three and when that node went down for planned maintenance our service didn't have other nodes to fall back to. This is, of course, our fault for not testing our assumptions better.

The following explains how this happened, what's the impact and a proposed solution how to prevent this for other people in the future:

### Problem Description

The code looks like this:

```scala
val hosts = List(
  "es1.example.com",
  "es2.example.com",
  "es3.example.com",
)

val config = ElasticProperties(
  hosts.map(host => s"http://${host}:9200").mkString(",")
)

// use config to build client
```
([scastie](https://scastie.scala-lang.org/IKKZAdH0QTCJN4iKjoCmCA))

At first glance this looks fine and passed our reviews, however the actual parsed data looks like this:

```scala
ElasticProperties(
  ArraySeq(
    ElasticNodeEndpoint(http,es1.example.com,9200,Some(/es2.example.com:9200,http://es3.example.com:9200)), 
    ElasticNodeEndpoint(http,http:,9200,Some(/es2.example.com:9200,http://es3.example.com:9200))
  ),
  Map()  
)
````

As you can see it has only 2 nodes instead of the expected 3 and the second one has no valid host. Nodes 2 and 3 are put into the "prefix" part which is also wrong.

The reason is that the expected format is `protocol://host:port,host:port,host:port` but instead we pass the protocol for every node like `protocol://host:port,protocol://host:port,protocol://host:port`. Imo this is very easy to get wrong, especially since technically you could connect to different hosts using different protocols, so specifying it for every host makes sense.

### Impact

Since there is no error or warning and it works in production (since node 1 is correctly configured), it's easy to have a false sense of safety and to assume there is redundancy and resilience as described by the official ES docs. 

In reality there's a single point of failure and if the first node is unavailable there is no fallback at all.

### Possible solutions

1. Deprecate/Remove the `String` input for `ElasticProperties` so people use the safer alternative.
2. Detect this problem during parsing and either fail or at least warn the user about it.
3. Update the docs to either use the safer alternative in examples and/or warn people about this pitfall in the String interface.

Personally I prefer (1), especially since even the `JavaClient` itself uses a struct per endpoint and using a type-safe interface in Java but not Scala is a bit sad.
That said, you might disagree and find the `String` interface convenient. Therefore I'd start with (2) and keep (1) as a possibly future step.

(3) would also be possible in addition so users copy the safer method by default.

Please let me know what you think 🙂
Thank you for your time reading this and for maintaining this awesome library! I'll try to put up a PR as soon as possible.

Cheers
~ Felix

**Comment by Philippus** [comment]
Fixed in https://github.com/Philippus/elastic4s/pull/2962.
