### ISSUE TITLE
Add Synonyms API support

### ISSUE THREAD

**Issue by NikKozh** [Philippus/elastic4s#3035]
Not so long ago ES has added [Synonyms API](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/synonyms-apis.html) for managing synonyms. It was beta functional, but now for Elastic 8.13 this feature marked as stable.

I haven't found these methods in elastic4s and **probably** will be contributing myself in some future, but maybe someone is already working on it?

**Comment by Philippus** [comment]
Sounds like a good addition!

**Comment by Philippus** [comment]
@NikKozh Would you mind if I started working on adding this API?
