### ISSUE TITLE
Can we set a timeOut as part of the EsClient Setting?

### ISSUE THREAD

**Issue by SarpongAbasimi** [Philippus/elastic4s#3158]
I keep getting this error in my tests.
Can we create a way to set timeout when building the ESClient? 

<img width="1108" alt="Screenshot 2024-09-17 at 18 28 37" src="https://github.com/user-attachments/assets/201a58ad-6aba-465d-bee8-6542917b1d33">

**Comment by SarpongAbasimi** [comment]
```scala
  private object CustomRequestConfigCallback extends RequestConfigCallback {
    override def customizeRequestConfig(requestConfigBuilder: RequestConfig.Builder): RequestConfig.Builder =
      requestConfigBuilder
        .setConnectionRequestTimeout(20000) // Increased timeout
        .setConnectTimeout(20000) // Increased timeout
        .setSocketTimeout(20000) // Increased timeout
  }
```

I think this answers my question but I still get the error when I run my `IT` tests

**Comment by SarpongAbasimi** [comment]
@Philippus  @vbehar @rauanmayemir closing this issue but just incase you have an answers feel free to let me know thanks.

**Comment by Philippus** [comment]
If you have a repo with a minimal reproducer we could take a look.
