### ISSUE TITLE
releases 7.17.3 and 7.17.4 use elasticsearch 8

### ISSUE THREAD

**Issue by OriHoch** [Philippus/elastic4s#3187]
seems like both 7.17.3 and 7.17.4 were released from incorrect branch that supports elasticsearch 8

v7.17.4 is identical to release/8.3.x:

https://github.com/Philippus/elastic4s/compare/v7.17.4...release/8.3.x

**Comment by Philippus** [comment]
Are there features you're missing in 7.17.2 ?

**Comment by OriHoch** [comment]
I guess the issue is due to the manual github workflow? I'm happy to implement a more automated github workflow for you to prevent such problems if you want or add some validations etc..

**Comment by Philippus** [comment]
7.17.3 and 7.17.4 releases were released before the current workflows. When I have some time I'll see if I can create one last proper version for Elasticsearch 7.17.x. Don't want to spend too much time on it though. Elasticsearch 8 has been out for a long time.

**Comment by Philippus** [comment]
I've released a new version `7.17.25-RC1`. Can you try it out? It's under the new groupId, e.g.:
```libraryDependencies += "nl.gn0s1s" %% "elastic4s-client-esjava" % "7.17.25-RC1"```

**Comment by OriHoch** [comment]
thanks, yes I tested it, it's good

**Comment by Philippus** [comment]
`7.17.25` has been released.
