### ISSUE TITLE
elastic4s-http-streams for pekko?

### ISSUE THREAD

**Issue by jmarreroc** [Philippus/elastic4s#3206]
I figured that current elastic4s-http-streams is strongly coupled with akka.
Could be possible to create one for pekko?
Is it possible to contribute it in this project?

**Comment by Philippus** [comment]
I'm contemplating migrating that package to pekko: https://github.com/Philippus/elastic4s/pull/3203. But, I don't think we can do that in the 8.x series.

**Comment by lenguyenthanh** [comment]
I agree that we should support both akka and pekko if there not much maintenance burden. There are still a lot of people are using akka.

**Comment by Philippus** [comment]
Added in https://github.com/Philippus/elastic4s/pull/3217.
